### ISSUE TITLE
How to add `exposed-modules` depending on a cabal flag?

### ISSUE THREAD

**Issue by soenkehahn** [sol/hpack#116]
I can't manage to create a `package.yaml` that allows to add `exposed-modules` depending on a cabal flag. This is roughly what I tried:

``` yaml
  when:
  - condition: flag(with-servant-aeson-specs)
    dependencies:
    - servant-aeson-specs ==0.2.* || ==0.3.* || ==0.4.*
    exposed-modules:
    - Servant.MatrixParam.AesonSpecs
```

But I get the following message from `hpack`:

```
WARNING: Ignoring unknown field "exposed-modules" in library section
servant-matrix-param.cabal is up-to-date
```

And the cabal file is missing the `exposed-modules`.

Is there a way to do this with `hpack`?

(Here's the relevant project, if that helps: https://github.com/plow-technologies/servant-matrix-param)
