### ISSUE TITLE
Add ghcjs-options

### ISSUE THREAD

**Issue by dbaynard** [sol/hpack#136]
GHCJS uses ghcjs-options, in a similar manner to ghc-options.

See https://www.reddit.com/r/haskell/comments/54knub/ghcjs_dedupe/d83vetj.

**Comment by dbaynard** [comment]
(Temporary workaround: _e.g._

```yaml
when:
- condition: impl(ghcjs >= 0.2.1)
  ghc-options: -dedupe
```
)
