### ISSUE TITLE
Cannot enable `build-type: Custom`

### ISSUE THREAD

**Issue by pmlodawski** [sol/hpack#160]
I tried all of this:
``` 
build-type: Custom
``` 
```
setup-depends: ... 
``` 
```
custom-setup: 
  dependencies:
    - foo
    - bar
```
but all results in: ```WARNING: Ignoring unknown field ... in package description```

How do I enable **Custom** build type? I see it was released recently, but I cannot use it.

**Comment by sol** [comment]
It works for me.  Here is a minimal example:

```yaml
name: foo

custom-setup: 
  dependencies:
    - foo
    - bar

library: {}
```
Please give a fully self-contained example that does not work for you, together with the output of `hpack --version`.
