### ISSUE TITLE
Shortcuts for executables and tests

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#161]
I think it would be nice to have shortcuts for defining executables and tests (and probably benchmarks too). Pretty much every package I define with executables and tests looks like this:

``` yaml
name: some-package
library: ...
executables:
  some-package: ...
tests:
  test: ...
```

That is, I have a single executable with the same name as the package and a single test suite with the name "test". I always wish it could be shortened to this:

``` yaml
name: some-package
library: ...
executable: ...
test: ...
```

The top level `executable: x` would be transformed into `executables: { some-package: x }`, and the `test` part would do the same. 

Is there any interest in this feature?
