### ISSUE TITLE
conditional on executable building

### ISSUE THREAD

**Issue by ababkin** [sol/hpack#163]
I'd like to be able to drive whether an executable builds or not with a flag. The executable has a lot of heavy dependencies (like `pandoc`) that are not shared by the library or other executables, so I'd like to avoid building these along with the executable if the flag is not enabled.

Currently i drive the executable building with a flag this way:
```
 my-exec:
    main: Main.hs
    source-dirs: backend
    dependencies:
      - aeson >= 1.1.0.0 && < 1.2
      - base >= 4.8 && < 5
      - bytestring >= 0.10 && < 0.11
      - pandoc >= 1.19.1.2
    when:
    - condition: flag(build-my-exec)
      then:
        buildable: true
      else:
        buildable: false
```

but unfortunately, even when the flag is disabled, the dependencies still get built (wasting the precious time and resources)

Is there a way to disable the whole executable section with a conditional based on flag? And if so, how would it look like?

Thanks
Alex

**Comment by liskin** [comment]
I think you can put those dependencies into `then:` and it would behave as you wanted. Arguably this isn't very good user experience, but I consider it a cabal's flaw, not hpack's.

**Comment by sol** [comment]
@ababkin works for me.  Below is an example.

```
$ cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
```

```yaml
name: hello

flags:
  foo:
    manual: true
    default: false

library: {}

executables:
  hpack:
    main: Main.hs
    dependencies:
      - foo
    when:
      condition: flag(foo)
      buildable: false
```

**Comment by ababkin** [comment]
thanks all, this had finally worked for me:

```
  my-exec:
    main: Main.hs
    source-dirs: service
    
    when:
    - condition: flag(build-my-exec)
      then:
        dependencies:
          - aeson >= 1.1.0.0 && < 1.2
          - base >= 4.8 && < 5
          - pandoc >= 1.19.1.2
        buildable: true
      else:
        buildable: false
```
