### ISSUE TITLE
js-sources tag being ignored

### ISSUE THREAD

**Issue by jfsagasti** [sol/hpack#166]
I'm using the new "js-sources" tag in the stack.yaml file, but when I'm building the project, this message is shown: **WARNING: Ignoring unknown field "js-sources" in library section**

I am just doing this:
```
library:
  source-dirs: src
  js-sources:
    - jsbits/*.js
```

Don't really know what is happening here yet. Any clues? Thanks!
