### ISSUE TITLE
Automatically make library dependency of test suite

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#167]
It would be nice if a package's library was automatically added as a dependency of its test suite. I can't think of many scenarios where I want to write a test suite that doesn't depend on the package. 

For example, consider this `package.yaml`:

``` yaml
name: example
library: {}
tests:
  test:
    dependencies: [example, ...]
```

The `test` dependency on `example` will pretty much always be there.
