### ISSUE TITLE
When there are multiple source directories, `.` can't be the first source directory.

### ISSUE THREAD

**Issue by crocket** [sol/hpack#168]
```
name: xmonad-configuration
synopsis: My XMonad Configuration
description: My XMonad Configuration
license: BSD3

dependencies:
  - base >=4.9 && <4.10
  - directory >=1.3 && <1.4
  - X11 >=1.8 && <1.9
  - xmonad-contrib >=0.13 && <0.14
  - xmonad >=0.13 && <0.14
  - containers
  - time

source-dirs:
  - .
  - lib

executables:
  xmonad-exec:
    main: xmonad.hs
```

produces

```
-- This file has been generated from package.yaml by hpack version 0.14.1.
--
-- see: https://github.com/sol/hpack

name:           xmonad-configuration
version:        0.0.0
synopsis:       My XMonad Configuration
description:    My XMonad Configuration
license:        BSD3
license-file:   LICENSE
build-type:     Simple
cabal-version:  >= 1.10

executable xmonad-exec
  main-is: xmonad.hs
  hs-source-dirs:
      .
    , lib
  build-depends:
      base >=4.9 && <4.10
    , directory >=1.3 && <1.4
    , X11 >=1.8 && <1.9
    , xmonad-contrib >=0.13 && <0.14
    , xmonad >=0.13 && <0.14
    , containers
    , time
  other-modules:
      XMonad.Maim
      XMonad.MyTheme
      XMonad.Scrot
  default-language: Haskell2010
```

cabal fails to parse `hs-source-dirs` probably because `.` is the first source directory. When `lib` is the first source directory, cabal doesn't fail to parse this .cabal file.

stack 1.3.2
hpack 0.14.1
ghc 8.0.2
