### ISSUE TITLE
Deprecate "executables" after 0.18.0 release?

### ISSUE THREAD

**Issue by sol** [sol/hpack#178]

**Comment by sol** [comment]
> My only input is that it might make more sense to keep executables instead of executable. Other fields that behave like this, like dependencies, are plural.

(moving this discussion here)

@tfausak That would mean we remove `executable` all together and only go with `executables`?  On the plus side that would be 100% backward-compatible, so we would not need a deprecation cycle.

It's just that reading

```yaml
executabels:
  main: Main.hs
```

feels weird to me, at least initially.

But in general I'm open to it.

**Comment by tfausak** [comment]
You're right, that is a little weird. I'm not sure which is better :confused: 

``` yaml
dependencies: base
dependencies: [ base ]
dependencies:
  - base

executables: { main: Main.hs }
executables: [ { main: Main.hs } ]
executables:
  main: Main.hs
```

On the other hand, reading multiple executables in the `executable` section is also a bit strange.

``` yaml
executable:
  one: { main: one.hs }
  two: { main: two.hs }
```

I don't have a super strong opinion either way.
