### ISSUE TITLE
Ignoring unknown field "executable" in package description

### ISSUE THREAD

**Issue by koxu1996** [sol/hpack#181]
I have simple **package.yaml** file:
```
name: test
version: 0.1.0.0

dependencies:
  - base >=4.8 && <4.9

library:
  source-dirs: src-lib
  exposed-modules:
    - Game

executable:
  main: Main.hs
  source-dirs: src-exec
  dependencies:
    - test
```
Running `stack build` result in:
`WARNING: Ignoring unknown field "executable" in package description`

I am not sure this is hpack or stack issue. Maybe I am doing something wrong?

**Comment by sol** [comment]
@koxu1996 Thank you for taking the time to open this issue!  The `executable`-field is only support since `hspack-0.18.0`, which is not used by `stack` yet.   For now you may want to use

```yaml
executables:
  test:
    main: Main.hs
    source-dirs: src-exec
    dependencies:
      - test
```
instead.
