### ISSUE TITLE
Allow dependencies to be a hash?

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#186]
Currently the `dependencies` field must be either a single element or a list of elements. Each element is either a string (like `'base == 4.9.1.0'`) or a hash (like `{ name: foo, path: ./foo }`). I think it would be nice to specify dependencies as a hash where the key is the package name and the value is the version constraint. For example:

``` yml
dependencies:

  # implies ==
  base: 4.9.1.0

  # wildcards
  bytestring: 0.10.*

  # comparisons
  text: '>= 1.2.2'

  # operators
  vector: '>= 0.11 && < 0.13'

  # no constraints
  deepseq: null

  # local, implies { name: foo }
  foo: { path: ./foo }

  # git, also implies name
  bar: { git: 'http://example.com', ref: master }
```

This would create ambiguity between a single dependency given as a hash and my proposed syntax. I would resolve that ambiguity by forbidding a single dependency to be given as a hash. In other words, to list a single local or Git dependency, you'd have to do this:

``` yml
dependencies: [ { name: foo, path: ./foo } ]
```

Without the list wrapping the hash, it would be parsed like this:

``` yml
dependencies: { name: foo, path: ./foo }
# dependencies: [ 'name == foo', 'path == ./foo' ]
```

If you think this is worth exploring I can probably come up with a PR to add it.

**Comment by mitchellwrosen** [comment]
I'm a little bit confused, is that hash syntax undocumented, or part of this proposal?

**Comment by tfausak** [comment]
The hash syntax is not part of my proposal. It's undocumented. I learned about it from other issues (Git #26, local #52) and the test suite ([Git dependency](https://github.com/sol/hpack/blob/8eda90ad3acd6f89380b1ad03fd5e87a932738f7/test/Hpack/ConfigSpec.hs#L225-L232), [local dependency](https://github.com/sol/hpack/blob/8eda90ad3acd6f89380b1ad03fd5e87a932738f7/test/Hpack/ConfigSpec.hs#L253-L259)).

**Comment by mitchellwrosen** [comment]
Huh, I don't understand that feature. Hpack just generates a cabal file, so how can a git repo or branch be relevant?

**Comment by tfausak** [comment]
It doesn't make sense to me either. I've never used it. The output `.cabal` file only includes the dependency names (see [`renderDependencies`](https://github.com/sol/hpack/blob/8eda90ad3acd6f89380b1ad03fd5e87a932738f7/src/Hpack/Run.hs#L268-L269)).

**Comment by sol** [comment]
git/local dependencies are used by [`tinc`](https://github.com/sol/tinc).

It may make sense to add support for them to `stack` too.

**Comment by tfausak** [comment]
Stack already handles local and Git dependencies through `stack.yaml`.

**Comment by sol** [comment]
@tfausak Sorry for the late reply.

In general I like how this looks.

What I don't like so much is the "no constraint"-case (`deepseq: null`).  Here I think the current syntax is more convenient.  And in many scenarios (e.g. with `stack`, `tinc` or `cabal freeze`) having no constraints is what you want (this is in particular true for in-house code, and not so much for libraries that you plan to publish).

So I'm not sure if I like this proposal enough to deprecate the current syntax in favor of it.  Which poses the question: Does this add enough to justify having two syntactic ways to express the same thing?

I think we had a discussion about his before, @soenkehahn?

**Comment by tfausak** [comment]
Sorry, I should have clarified in my original comment: I don't want to deprecate the current list syntax; I want to add a hash syntax for when you have lots of dependencies with constraints. 

I agree that the no constraint case is a little weird. There are two alternatives that could work: specifying a wildcard (`deepseq: '*'`) or not specifying anything (`deepseq:`). Not specifying anything looks a little weird but makes this require the same number of keystrokes as the list syntax. 

I'm not sure if it's worth having two ways to express the same thing. I like the hash approach because it clearly separates the package names from their constraints. I think most YAML syntax highlighters will color keys differently that values, which should make picking out dependencies easier. Also hashes aren't ordered like lists are, so pretty printing them and sorting the keys is a reasonable thing to do.

**Comment by liskin** [comment]
I think this is a great idea, and it improves the usability of DRY features of YAML.
An example from our project:

We wish to have something like this in our `package_common.yaml`:
```yaml
- &unit-tests
  source-dirs: test
  main: Tests.hs
  dependencies:
    - QuickCheck >=2.5 && <3
    - tasty ==0.11.*
    - tasty-hunit ==0.9.*
    - tasty-quickcheck ==0.8.*
```
and then in `package.yaml` just do:
```yaml
name: package1

_common: !include "../package_common.yaml"

library:
  source-dirs: src
tests:
  unit-tests: *unit-tests
```
But then `unit-tests` don't have `package1` as a dependency, and YAML won't let us add something to `dependencies` of `unit-tests`.
We worked around it by using `name: &name package1` and then having `- *name` in `dependencies` of `&unit-tests` but if we ever need to add another dependency, we're in trouble.

With your proposal, the whole thing could look like this:
```yaml
- &unit-tests
  source-dirs: test
  main: Tests.hs
  dependencies: &unit-tests-dependencies
    QuickCheck: '>=2.5 && <3'
    tasty: '==0.11.*'
    tasty-hunit: '==0.9.*'
    tasty-quickcheck: '==0.8.*'
```
```yaml
name: package1

_common: !include "../package_common.yaml"

library:
  source-dirs: src
tests:
  unit-tests:
    <<: *unit-tests
    dependencies:
      <<: *unit-tests-dependencies
      package1:
      some-other-dependency: '==0.1.*'
```

Admittedly this is quite verbose so the `&name`/`*name` hack is still useful for the common case, but at least this makes it possible to declare named dependency lists.
