### ISSUE TITLE
Omit inference of modules that are referenced in conditionals

### ISSUE THREAD

**Issue by scott-fleischman** [sol/hpack#209]
I propose that any modules appearing in `exposed-modules` and/or `other-modules` within a conditional are excluded from consideration when inferring `exposed-modules` and/or `other-modules` at the top level.

For me, the intuition behind this proposal is that any module in a conditional is likely problematic outside of the conditional (platform-specific or is associated with dependencies in the conditional).

I believe this would best the best default setup that would "just work" for most cases.

This is a continuation of the discussion from https://github.com/sol/hpack/commit/6a55600c5fd86be5ae95eb2f7b217c898519a676

**Comment by scott-fleischman** [comment]
If both `exposed-modules` and `other-modules` are specified at the top level, specifying modules in conditionals seems behave fine (and might be the "recommended" way to use hpack when specifying modules in conditionals).

I will try to enumerate some of the cases. Say we have a source directory with 8 modules: `A`, `B`, `C`, `D`, `E`, `F`, `G`, `H`.

As I see it there are 16 main cases, depending on whether
A. `exposed-modules` defined at top-level
B. `other-modules` defined at top-level
C. `exposed-modules` defined within conditional
D. `other-modules` defined within conditional

### 1. (None specified)
* Inferred `exposed-modules`: `{A,B,C,D,E,F,G,H}`
* Inferred `other-modules`: `{}`

### 2. Case A
```
exposed-modules:
- A
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{B,C,D,E,F,G,H}`

### 3. Case B
```
other-modules:
- A
```
* Inferred `exposed-modules`: `{B,C,D,E,F,G,H}`
* Inferred `other-modules`: `{A}`

### 4. Case A,B
```
other-modules:
- A
```
* Inferred `exposed-modules`: `{B,C,D,E,F,G,H}`
* Inferred `other-modules`: `{A}`

### 5. Case C
```
when:
- condition: ...
  exposed-modules:
  - A
```
* Inferred `exposed-modules`: `{B,C,D,E,F,G,H}`
* Inferred `other-modules`: `{}`

### 6. Case A,C
```
exposed-modules:
- A
when:
- condition: ...
  exposed-modules:
  - B
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{C,D,E,F,G,H}`

### 7. Case B,C
```
other-modules:
- A
when:
- condition: ...
  exposed-modules:
  - B
```
* Inferred `exposed-modules`: `{C,D,E,F,G,H}`
* Inferred `other-modules`: `{A}`

### 8. Case A,B,C
```
exposed-modules:
- A
other-modules:
- B
when:
- condition: ...
  exposed-modules:
  - C
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{B}`

### 9. Case D
```
when:
- condition: ...
  other-modules:
  - A
```
* Inferred `exposed-modules`: `{B,C,D,E,F,G,H}`
* Inferred `other-modules`: `{}`

### 10. Case A,D
```
exposed-modules:
- A
when:
- condition: ...
  other-modules:
  - B
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{C,D,E,F,G,H}`

### 11. Case B,D
```
other-modules:
- A
when:
- condition: ...
  other-modules:
  - B
```
* Inferred `exposed-modules`: `{C,D,E,F,G,H}`
* Inferred `other-modules`: `{A}`

### 12. Case A,B,D
```
exposed-modules:
- A
other-modules:
- B
when:
- condition: ...
  other-modules:
  - C
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{B}`

### 13. Case C,D
```
when:
- condition: ...
  exposed-modules:
  - A
  other-modules:
  - B
```
* Inferred `exposed-modules`: `{C,D,E,F,G,H}`
* Inferred `other-modules`: `{}`

### 14. Case A,C,D
```
exposed-modules:
- A
when:
- condition: ...
  exposed-modules:
  - B
  other-modules:
  - C
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{D,E,F,G,H}`

### 15. Case B,C,D
```
other-modules:
- A
when:
- condition: ...
  exposed-modules:
  - B
  other-modules:
  - C
```
* Inferred `exposed-modules`: `{D,E,F,G,H}`
* Inferred `other-modules`: `{A}`

### 16. Case A,B,C,D
```
exposed-modules:
- A
other-modules:
- B
when:
- condition: ...
  exposed-modules:
  - C
  other-modules:
  - D
```
* Inferred `exposed-modules`: `{A}`
* Inferred `other-modules`: `{B}`

**Comment by scott-fleischman** [comment]
For me, the intuition behind this proposal is that any module in a conditional is likely problematic outside of the conditional (platform-specific or is associated with dependencies in the conditional).

**Comment by scott-fleischman** [comment]
In one of our projects, we are doing an expanded Case 6 above, where we specify exposed-modules at the top level, then have conditionals for flags for use of Persistent and GHCJS. (For better or worse, it is using the flags at the package/cabal level to avoid rather gnarly CPP conditionals within the Haskell code.)

It looks something like:
```
exposed-modules:
- A
- B
when:
- condition: impl(ghcjs -any)
  exposed-modules:
  - C
  - D
  dependencies:
  - ghcjs-base
  - ..
- condition: flag(persistent)
  then:
    exposed-modules: 
    - E
    - F
    dependencies:
    - ...
  else
    exposed-modules:
    - G
    - H
    dependencies:
    - ...
```

In our case, I just want the top-level `other-modules` to be empty. I can specify this, but my proposed solution above will also accomplish this (provided I don't have any other files than `{A,B,C,D,E,F,G,H}` -- and even if I did, this behavior would help identify the rogue files.).
