### ISSUE TITLE
Inferring modules in conditionals?

### ISSUE THREAD

**Issue by sol** [sol/hpack#228]
It might be sensible to infer modules in conditionals when `source-dirs` is specified.  For executables we already do this (inferring `other-modules`).  What do we want to do for libraries here?

### Example

Given the following files:

```
src/Foo.hs
windows/Bar.hs
posix/Bar.hs
```

```yaml
# package.yaml
library:
  source-dirs: src
  when:
    condition: os(windows)
    then:
      source-dirs: windows
    else:
     source-dirs: posix
```

Library top-level we infer everything as `exposed-modules` if nothing else is specify.  What do we want to infer inside the conditionals?

As I argued before, it may make sense to infer `other-modules` inside the conditionals, which give us the following:

```cabal
library
  hs-source-dirs: src
  exposed-modules: Foo
  if os(windows)
    hs-source-dirs: windows
    other-modules: Bar
  else
    hs-source-dirs: posix
    other-modules: Bar
```

@scott-fleischman @borsboom Any opinions?
