### ISSUE TITLE
Ignoring unknown field "other-modules"

### ISSUE THREAD

**Issue by lehins** [sol/hpack#229]
Whenever `other-modules` is used with conditionals `hpack` generates an error:

```
$ hpack
WARNING: Ignoring unknown field "other-modules" in library section
``` 

For example:

```
  when:
  - condition: os(windows)
    then:
      other-modules:
      - MyModule.Windows
    else:
      other-modules:
      - MyModule.Unix
```

Should translate into a legal .cabal syntax:

```
if os(windows)
      other-modules: MyModule.Windows
  else
      other-modules: MyModule.Unix
```
