### ISSUE TITLE
Allow dependency constraints to be numbers

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#234]
You can specify dependencies as a hash where the keys are package names and the values are either nothing, strings, or hashes. It would be nice if the values could be numbers too. For example:

``` yaml
dependencies:
  # This works fine because `0.5.7.1` is parsed as a string.
  http-client: 0.5.7.1
  # This doesn't work because `0.11` is parsed as a number.
  http-types: 0.11
```

This is the exact error that I see:

```
.../package.yaml: Error in $.dependencies['http-types']: expected Null, Object, or String, encountered Number
```
