### ISSUE TITLE
hpack 0.21.1 generates broken cabal file for stack 1.6.1

### ISSUE THREAD

**Issue by felixonmars** [sol/hpack#236]
When running Setup with the generated stack.cabal, the following error occurs:

```
Configuring stack-1.6.1...
Setup: Duplicate modules in library: System.Terminal
```

The error is not present when generated with hpack 0.20.0.

Running diff on the generated cabal file suggests that the module were generated into an irrelevant place:

```
-  if os(windows)
-    hs-source-dirs:
-        src/windows/
-  else
-    hs-source-dirs:
-        src/unix/
<snip>
+  if os(windows)
+    other-modules:
+        System.Terminal
+    hs-source-dirs:
+        src/windows/
+  else
+    other-modules:
+        System.Terminal
+    hs-source-dirs:
+        src/unix/
```

In the package.yaml file the module was only defined once under library.exposed-modules, and the condition part is simply about hs-source-dirs, which the old hpack generates correctly:

```
  when:
  - condition: 'os(windows)'
    then:
      source-dirs: src/windows/
    else:
      source-dirs: src/unix/
```
