### ISSUE TITLE
Add shorthand syntax for defaults

### ISSUE THREAD

**Issue by sol** [sol/hpack#241]
e.g. `defaults: hspec/hspec@2.4.4` becomes

```
defaults:
  github: hspec/hspec
  ref: 2.4.4
  path: .hpack/defaults.yaml
```
