### ISSUE TITLE
Defaults: directory traversal attack

### ISSUE THREAD

**Issue by quasicomputational** [sol/hpack#244]
I do not think that this implementation of defaults is secure against directory traversal. Consider this package.yaml:
```
defaults:
  github: example/evil
  ref: master
  path: ../../../../.ssh/id_rsa
```
That's going to fail because an SSH private key (probably?) won't parse as YAML, but I am sure someone cleverer than me can lever this into a workable attack. There are two different aspects to this:
1. The ability to drop random files anywhere user-writable when hpack is run (very possible, fairly dangerous)
2. The ability to read any user-readable file and potentially include parts of them in the generated cabal file (harder to exploit but far from impossible, and very very very dangerous).
