### ISSUE TITLE
Inheritance, auto-concatenation and conditionals can lead to surprising order of ghc-options

### ISSUE THREAD

**Issue by quasicomputational** [sol/hpack#255]
Given this package.yaml:
```
name: test

ghc-options: A
when:
  condition: impl(ghc >= 8.2)
  ghc-options: B

library:
  ghc-options: C
  when:
    condition: impl(ghc >= 8.0)
    ghc-options: D
```
this is what hpack generates for the library section:
```
library
  other-modules:
      Paths_test
  ghc-options: A C
  if impl(ghc >= 8.2)
    ghc-options: B
  if impl(ghc >= 8.0)
    ghc-options: D
```

On GHC 8.2, this will lead to the options being passed to GHC in the order A C B D (i.e., the lexical order in the generated cabal file). I contend that this is not the user's intent, and that A B C D would be better, on the general principle that specific should be able to override general (and hence go later) and C is more specific than B.

cabal doesn't complain about multiple ghc-options fields. This isn't *quite* documented behaviour, but nearly: ("if two conditional sections appear at the same nesting level, properties specified in the latter will come after properties specified in the former")[http://cabal.readthedocs.io/en/latest/developing-packages.html#meaning-of-field-values-when-using-conditionals]; difference being that the A and C options aren't in conditionals. So maybe this would be better to generate:
```
library
  other-modules:
      Paths_test
  ghc-options: A
  if impl(ghc >= 8.2)
    ghc-options: B
  ghc-options: C
  if impl(ghc >= 8.0)
    ghc-options: D
```

**Comment by quasicomputational** [comment]
Another option: abuse `if true` to get the desired ordering. This is also an effective workaround today!

**Comment by sol** [comment]
@quasicomputational can you motivate how this hurts you in practice?

**Comment by quasicomputational** [comment]
Here's a variation of the code that tripped me up:
```
when:
  condition: impl(ghc >= 8.0)
  ghc-options: -Weverything

executable:
  ghc-options: -Wno-missing-import-lists
```

On GHC 8.0 and 8.2, the arguments that get passed to GHC are, in order, "-Wno-missing-import-lists -Weverything". Which means that "-Wmissing-import-lists" is in effect, which surprised me greatly when it happened.

**Comment by sol** [comment]
Would
```yaml
when:
  condition: impl(ghc >= 8.0)
  then:
    ghc-options: -Weverything -Wno-missing-import-lists
  else:
    ghc-options: -Wno-missing-import-lists
```
work?  Or do you need `-Wno-missing-import-lists` for the executable only?

**Comment by quasicomputational** [comment]
The workaround I used was this:
```
when:
  condition: impl(ghc >= 8.0)
  ghc-options: -Weverything

executable:
  when:
    condition: true
    ghc-options: -Wno-missing-import-lists
```

That gets the expected ordering, and it's purely a local change and hence easy to rip out if it gets fixed.

This isn't ruining my day or blocking me or anything, but I do think that it's a bug and worth fixing at some point.
