### ISSUE TITLE
Top-level use of verbatim can result in invalid .cabal file

### ISSUE THREAD

**Issue by sol** [sol/hpack#280]
Steps to reproduce:

```yaml
# package.yaml
name:        test
version:     '0.1.0.0'

verbatim: |
  data-dir:    data/

library:
  exposed-modules:
    - Test.hs
```
Generated .cabal:
```
# test.cabal
name:           test
version:        0.1.0.0
build-type:     Simple
cabal-version:  >= 1.10

library
  exposed-modules:
      Test.hs
  other-modules:
      Paths_test
  default-language: Haskell2010

data-dir:    data/
```
This will be rejected by Cabal with `Plain fields are not allowed in between stanzas`.

Thanks to @vlatkoB for reporting this.
