### ISSUE TITLE
how to define a conditional test suite ?

### ISSUE THREAD

**Issue by simonmichael** [sol/hpack#285]
I'd like to skip doctests for GHC 8.4, due to https://github.com/sol/doctest/issues/199. I've tried:
```yaml
tests:

  when:
  - condition: (!impl(ghc >= 8.4))
    doctests:
      main: doctests.hs
      source-dirs: tests
      dependencies:
      - doctest >=0.8
      - Glob >=0.7

  hunittests:
    ...

# "Error in $.tests.when: expected record (:*:), encountered Array"
```
and
```yaml
tests:

  doctests:
    main: doctests.hs
    source-dirs: tests
    dependencies:
    - doctest >=0.8
    - Glob >=0.7
    when:
    - condition: (!impl(ghc >= 8.4))
      buildable: false

# doctests test suite still runs
```

**Comment by sol** [comment]
@simonmichael I would expect the second option to work.  Can you provide your full `package.yaml` and the output of `hpack --version` or `stack --version`.

**Comment by sol** [comment]
@simonmichael Is your `condition` correct?  Should that be `impl(ghc >= 8.4)` instead?

**Comment by simonmichael** [comment]
You're right, and now it works. Thank you very much @sol. For the record, here's my working solution:
```
tests:

  doctests:
    main: doctests.hs
    source-dirs: tests
    dependencies:
    - doctest >=0.8
    - Glob >=0.7
    # doctest won't run with ghc 8.4 on mac right now, https://github.com/sol/hpack/issues/199
    when:
    - condition: impl(ghc >= 8.4) && os(darwin)
      buildable: false
```
