### ISSUE TITLE
Add doctest example

### ISSUE THREAD

**Issue by benjaminweb** [sol/hpack#289]
Setup
------------

* Create directory `test`.
* Create file `test/Doctest.hs`:
```haskell
Test.DocTest
main :: IO ()
main = doctest ["-isrc", "src/Main.hs", "src/MyModule.hs"]
```

* Add to `package.yaml`:
```yaml
tests:
    doctest:
      main: Doctests.hs
      source-dirs:
        - test
      dependencies:
        - doctest
```

Execution
----------
* execute `hpack` in project root directory.
* run doctests with `stack test` in root directory.
