### ISSUE TITLE
Support for os-specific things (dependencies, etc.)

### ISSUE THREAD

**Issue by sol** [sol/hpack#29]
We still need to settle on some concrete syntax here.  Ideas?

**Comment by sol** [comment]
Ideally the approach can be extended to `arch` and `flag`, if we ever reach the point that we need it.

Relevant Cabal documentation: https://www.haskell.org/cabal/users-guide/developing-packages.html#conditional-blocks

cc @Fuuzetsu @soenkehahn

**Comment by sol** [comment]
Some ideas:

```yaml
dependencies:
  - name: Win32
    when: os(windows) && arch(i386)
  - name: unix
    when: "!os(windows)"

windows-i386-dependencies:
  - Win32
unix-dependencies:
  - unix
```

```yaml
os:
  windows:
    arch:
      i386:
        dependencies: Win32
  other:
    dependencies: unix
```

```yaml
if:
  condition: os(windows) && arch(i386)
  then:
    dependencies:
      - Win32
  else:
    dependencies:
      - unix
```

**Comment by sol** [comment]
```yaml
when:
  condition: os(windows) && arch(i386)
  dependencies:
    - Win32
when:
  condition: "!os(windows)"
  dependencies:
    - unix
```

**Comment by sol** [comment]
when:
  os: windows
  arch: i386
  dependencies:
    - Win32

when:
  os: "!windows"
  dependencies:
    - unix

**Comment by sol** [comment]
```yaml
when:
  condition: os(windows) && arch(i386)
  then:
    dependencies:
      - Win32
  else:
    dependencies:
      - unix
```

**Comment by sol** [comment]
For flags:

```yaml
flags:
  integration-tests:
    description: Run the integration test suite
    manual: yes
    default: no
```
or
```yaml
flags:
  - name: integration-tests:
    description: Run the integration test suite
    manual: yes
    default: no
```

**Comment by qoelet** [comment]
```yaml
when:
  - condition: os(windows) && arch(i386)
    dependencies:
      - Win32
  - condition: "!os(windows)"
    dependencies:
      - unix
```

**Comment by jkarni** [comment]
Any decisions? The last one, and either of the flag proposals, sound good to me. Happy to help implementing.

**Comment by sol** [comment]
Yes, sounds good to me. Maybe the first flags proposal?

**Comment by phadej** [comment]
I long avoided need to flags, but atm I just cannot avoid it anymore. So I'd like to see this happen. I'd like the
```yaml
flags:
  integration-tests:
    description: Run the integration test suite
    manual: yes
    default: no
```

and

```yaml
when:
  - condition: os(windows) && arch(i386)
    dependencies:
      - Win32
  - condition: "!os(windows)"
    dependencies:
      - unix
  - condition: flag(integration-tests)
    dependencies:
      - QuickCheck
```
