### ISSUE TITLE
'SourceDependencies' exist but can't work

### ISSUE THREAD

**Issue by quasicomputational** [sol/hpack#320]
I found in the course of hacking on #318 that this syntax is supported:

```
name: foo
version: 0

library:
  dependencies:
    Cabal:
      github: haskell/cabal
      ref: d53b6e0d908dfedfdf4337b2935519fb1d689e76
      subdir: Cabal
```

and produces this output:

```
name:           foo
version:        0
build-type:     Simple
cabal-version:  >= 1.10

library
  other-modules:
      Paths_foo
  build-depends:
      Cabal
  default-language: Haskell2010
```

I'm not sure I see the point of that: there's no way to put the information about the Git repo (or a local package) into the output `.cabal` file. Both Stack and (soon) cabal-install support pulling non-Hackage dependencies from a Git repo, but they read the information from `stack.yaml` and `cabal.project` respectively.

It's also totally undocumented. I'm quite tempted to rip it out on the grounds that it won't, and can't, do what the user would like it to do.

This was added in 64465789ba594c044fa2eec1e5df787c5dce3a27, by @sol and @soenkehahn. @qoelet added some features later. Thoughts? Is there a use case here I'm not seeing?
