### ISSUE TITLE
Add a format command.

### ISSUE THREAD

**Issue by philderbeast** [sol/hpack#341]
Please add a `format` command to hpack with an `--inplace` option to overwrite the `package.yaml` file.

    hpack format --inplace

> * When using Dhall it's more likely that you get git conflicts when rebasing/merging (yes, commas again)
SOURCE: https://github.com/BlockScope/hpack-dhall/issues/3#issuecomment-418572726

If a `format` command was added to hpack then use of this command could help to reduce the chance of git conflicts when rebasing/merging.

### Differences

I'm currently adding some real world golden tests for the executable `dhall-hpack-yaml` from package `hpack-dhall`, trying to generate output that matches hpack's `package.yaml` and stack's `package.yaml`. The kinds of differences I've seen between handwritten and generated `package.yaml` files are;

* Indentation
```
dependencies:
- base >= 4.9 && < 5
- bytestring

dependencies:
  - base >= 4.9 && < 5
  - bytestring
```
* Field order
```
category: Development
maintainer: Simon Hengel <sol@typeful.net>
extra-source-files: CHANGELOG.md
github: sol/hpack

maintainer: Simon Hengel <sol@typeful.net>
github: sol/hpack
category: Development
extra-source-files:
  - CHANGELOG.md
```
* Single element lists
```
dependencies: hpack

dependencies:
    - hpack
```
* Empty lines
```
executable:
  source-dirs: driver
  dependencies: hpack
  main: Main.hs
tests:
  spec:

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
    - hpack

tests:
  spec:
```
* Version numbers
```
name: stack
version: ! '''1.10.0'''

name: stack
version: '1.10.0'

name: hpack
version: 0.31.1
```
