### ISSUE TITLE
Duplicate exposed-modules

### ISSUE THREAD

**Issue by chrissound** [sol/hpack#356]
This seems to be caused by `source-dirs` being specified at the root level, as well as under `library`.

This is a simplified minimal case - so possibly it might not make sense, the actual file I'm using has a library+executable defined hence the need for the  root `source-dirs`.

minimal:
```
source-dirs: src
executables:
  pitanga:
    main: Main.main
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.15
name: platinumpitanga
version: '1.0.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
library:
  source-dirs: src
```

My actual hpack.yaml:
```
source-dirs: src
executables:
  pitanga:
    main: Main.main
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.15
- turtle
- aeson-pretty
- strings
- rainbow
- lens
- aeson
- bytestring
- split
- text
- time
- old-locale
- directory
- pretty-simple
- string-conversions
- optparse-applicative
- vector
- attoparsec
name: platinumpitanga
version: '1.0.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
library:
  source-dirs: src
```

Minmal generates:

```
cabal-version: 1.12

-- This file has been generated from package.yaml by hpack version 0.31.2.
--
-- see: https://github.com/sol/hpack
--
-- hash: 583e36627543e61f7831d296258c5ae42ec7226e08ed7c7f1c88136717c37ce7

name:           platinumpitanga
version:        1.0.0.0
author:         Chris Stryczynski
maintainer:     Chris Stryczynski
license:        BSD3
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    ChangeLog.md

library
  exposed-modules:
      Common
      Export
      Log
      Main
      MyDebug
      ResumeTask
      StopTask
      Types
      Common
      Export
      Log
      Main
      MyDebug
      ResumeTask
      StopTask
      Types
  other-modules:
      Paths_platinumpitanga
  hs-source-dirs:
      src
      src
  default-extensions: LambdaCase
  build-depends:
      base >=4.11 && <4.15
  default-language: Haskell2010

executable pitanga
  main-is: Main.hs
  other-modules:
      Common
      Export
      Log
      MyDebug
      ResumeTask
      StopTask
      Types
      Paths_platinumpitanga
  hs-source-dirs:
      src
  default-extensions: LambdaCase
  ghc-options: -main-is Main.main
  build-depends:
      base >=4.11 && <4.15
  default-language: Haskell2010

```

**Comment by chrissound** [comment]
This can be worked around (or perhaps I was using the wrong syntax in the first place), by setting `source-dirs` under the executable, as opposed to the root level / indent.

In other words:

```
source-dirs: src
executables:
  pitanga:
    main: Main.main
```

to

```
executables:
  pitanga:
    source-dirs: src
    main: Main.main
```
