### ISSUE TITLE
Ability to set custom options for a flag

### ISSUE THREAD

**Issue by googleson78** [sol/hpack#359]
I can't find a way to set "custom" options for a flag.

This is useful with [liquidhaskell-cabal](https://github.com/spinda/liquidhaskell-cabal-demo/blob/3ad5461e831ade9da23b81a440265113d1a66ee0/liquidhaskell-cabal-demo.cabal#L49) for example. Right now `hpack` just ignores it.

Can we allow this?

**Comment by quasicomputational** [comment]
`verbatim` ought to cover this use-case today, and if it doesn't, that's a bug.

```yaml
executables:
  ffi:
    main-is: FFI.hs
    verbatim:
      x-liquidhaskell-options: --diff
```
