### ISSUE TITLE
Support haddock-options

### ISSUE THREAD

**Issue by isovector** [sol/hpack#360]
There's a bug in haddock that doesn't allow it to play nicely with GHC plugins (see https://github.com/haskell/haddock/issues/900). The workaround is to enable some custom flags during haddock (https://github.com/haskell/haddock/issues/900#issuecomment-489607711), but `hpack` doesn't appear to support `haddock-options`.

**Comment by quasicomputational** [comment]
For the time being, `verbatim` options can be used to provide `haddock-options`, at least.

**Comment by Avi-D-coder** [comment]
@quasicomputational How can `verbatim` be used to set `haddock-options`? Where in `package.yaml` would I put it?

**Comment by quasicomputational** [comment]
Oh - apparently `haddock-options` isn't a valid field in package descriptions anyway (haskell/cabal#926). So, just stick it in `cabal.project` or `stack.yaml`, since there's not actually anything hpack can do until the package description knows about `haddock-options`.

**Comment by isovector** [comment]
Sorry, so what exactly is the fix here?

**Comment by Avi-D-coder** [comment]
@isovector This is the closest I've gotten, but I still have to comment out ` - -fplugin=Polysemy.Plugin` to run haddock.

stack.yaml
```yaml
build:
  haddock-arguments:
    haddock-args:
    - "--optghc=-fdefer-type-errors"
    - "--optghc=-fno-warn-deferred-type-errors"
```
