### ISSUE TITLE
Empty then block in a conditional breaks hackage

### ISSUE THREAD

**Issue by isovector** [sol/hpack#362]
I have this stanza:

```yaml
library:
  ghc-options: -Wall
  source-dirs: src
  other-modules: Polysemy.Internal.PluginLookup

  when:
    - condition: flag(error-messages)
      then: {}
      else:
        cpp-options: -DNO_ERROR_MESSAGES
```

which results in the following `cabal`:

```
  if flag(error-messages)
  else
    cpp-options: -DNO_ERROR_MESSAGES
```

which when I try to upload to hackage, explodes:

```
Checking package 'polysemy' for common mistakes
Uploading polysemy-0.5.0.0.tar.gz... unhandled status code: 400
Error: Invalid package

polysemy-0.5.0.0/polysemy.cabal:93:0: [v2.0] 'then' branch of 'if' is empty
```

**Comment by quasicomputational** [comment]
Hmm. This is a sensible thing for Hackage to reject. You can express this by negating the condition:

```yaml
library:
  ghc-options: -Wall
  source-dirs: src
  other-modules: Polysemy.Internal.PluginLookup

  when:
    - condition: "!flag(error-messages)"
      then:
        cpp-options: -DNO_ERROR_MESSAGES
```

(note that you do have to quote the condition, since `!` is syntax in YAML)

hpack could detect this and automatically apply this negation transformation. It'd hardly be more magic than hpack already uses. The only question is whether this type of `then`-less condition is something to be tolerated, or if it's a smell that shouldn't be encouraged; my inclination is it's harmless, but I don't feel strongly enough about it to do the implementing.
