### ISSUE TITLE
The github field is finicky

### ISSUE THREAD

**Issue by isovector** [sol/hpack#365]
Consider the following hpack metadata :

```yaml
name:                cmptype
version:             0.1.0.0
github:              "https://github.com/isovector/type-sets/tree/master/cmptype"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"
```

This `github` field looks fine, right? But hpack mangles it when generating the cabal file:

```
cabal-version: 1.12

-- This file has been generated from package.yaml by hpack version 0.31.2.
--
-- see: https://github.com/sol/hpack
--
-- hash: 961cf4bb432f401123d81aa11c22e60aaab80702b2adb69c1bd87dcf6d8881c9

name:           cmptype
version:        0.1.0.0
homepage:       https://github.com/https://github.com/isovector/type-sets/tree/master/cmptype#readme
bug-reports:    https://github.com/https://github.com/isovector/type-sets/tree/master/cmptype/issues
author:         Sandy Maguire
maintainer:     sandy@sandymaguire.me
copyright:      2019 Sandy Maguire
license:        BSD3
```

egads!
