### ISSUE TITLE
one conditional can mask another

### ISSUE THREAD

**Issue by simonmichael** [sol/hpack#379]
With two similar conditionals, only the last one appears in the .cabal file.

package.yaml:
```
    when:
    - condition: (impl(ghc >= 8.10))
      buildable: false

    when:
    - condition: (impl(ghc < 8.2))
      buildable: false
```
.cabal file:
```
  if (impl(ghc < 8.2))
    buildable: False
  default-language: Haskell2010
```

Seen with stack 2.1.3's hpack 0.31.2, and also with hpack 0.33.0. When run directly, hpack also warns:
```
    when:
    - condition: (impl(ghc >= 8.10))
      buildable: false
```

I expected both conditionals to appear in the .cabal file.

**Comment by sol** [comment]
This is due to how JSON works (and YAML for that matter).  You can't define an object with duplicate fields names.  If you do, one of them will be ignored.

I added the warning so that these kind of situations are easier to spot.

Use the following instead:

```
when:
- condition: (impl(ghc >= 8.10))
  buildable: false

- condition: (impl(ghc < 8.2))
  buildable: false
```
