### ISSUE TITLE
Add support for visibility: public

### ISSUE THREAD

**Issue by expipiplus1** [sol/hpack#382]
Thanks for the super tool!

It would be really nice to have support for multiple public libraries: https://fgaz.me/posts/2019-11-14-cabal-multiple-libraries/

At the moment it seems possible to do with `verbatim: visibility: public` as below, but it seems nasty to have to put these libraries in `internal-libraries`.

```yaml
internal-libraries:
  foo:
    source-dirs: foo
    verbatim:
      visibility: public
    dependencies:
      - base < 4.14
```

**Comment by sol** [comment]
@expipiplus1 can you please try https://github.com/sol/hpack/pull/385?  Does this work for you?

**Comment by expipiplus1** [comment]
@sol, works great, thanks!

**Comment by sol** [comment]
@Ptival I didn't have the need for this myself, but if having a dependency on a public library doesn't work then this is probably something we want to fix.  If you can provide a minimal test case (as I understand it, we would need two packages for this, one that exports the library and one that depends on it), then I'll try to find the time to fix it.

**Comment by expipiplus1** [comment]
@ptival, I didn't try to import such a package using hpack, no. From what I
understand you're talking about the dual of this issue.

**Comment by Ptival** [comment]
Yes, it is indeed the other side of the picture.

@sol 

In terms of minimal example, if you write a `package.yaml` like:

```
dependencies:
  - base
  - package
  - package:library

library:
  other-modules: []

name: my-other-package

verbatim:
  cabal-version: 3.0
```

The output is:

```
cabal-version: 3.0

-- This file has been generated from package.yaml by hpack version 0.34.1.
--
-- see: https://github.com/sol/hpack

name:           my-other-package
version:        0.0.0
build-type:     Simple

library
  build-depends:
      base
    , package
  default-language: Haskell2010
```

When it should be:

```
cabal-version: 3.0

-- This file has been generated from package.yaml by hpack version 0.34.1.
--
-- see: https://github.com/sol/hpack

name:           my-other-package
version:        0.0.0
build-type:     Simple

library
  build-depends:
      base
    , package
    , package:library
  default-language: Haskell2010
```

Without it, `my-other-package` will not be able to import modules from `package:library`.

**Comment by sol** [comment]
For me

```yaml
dependencies:
  - base
  - package
  - package:library
```
results in a parse error.  @Ptival what version of `hpack` are you using?

We want to address this, but for the meantime, this can be used as a workaround:
```yaml
dependencies:
  - base
  - package
  - name: package:library
```
