### ISSUE TITLE
Cannot compose an internal-library dependency

### ISSUE THREAD

**Issue by JosephLucas** [sol/hpack#386]
Hi,

For this project structure
```
bar
├── InternalLibName
│   └── Exposed.hs
├── Main.hs
└── package.yaml
```

I would like to use this package.yaml 
```
executable:
  main: Main.hs
  dependencies: 
    - base == 4.*
    - internal-lib-name

internal-libraries: 
  internal-lib-name:
    exposed-modules: 
      InternalLibName.Exposed
    dependencies:
      - base
      - text
```
But running 
```
hpack && cabal build
```
returns the error
```
InternalLibName/Exposed.hs:2:1: error:
    Could not load module ‘Data.Text’
    It is a member of the hidden package ‘text-1.2.3.1’.
    Perhaps you need to add ‘text’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```
The only way I found to solve this error is to put the `text` dependency on top
```
dependencies:
    - text

executable:
  main: Main.hs
  dependencies: 
    - base == 4.*
    - internal-lib-name

internal-libraries: 
  internal-lib-name:
    exposed-modules: 
      InternalLibName.Exposed
    dependencies:
      - base
```

IMO, declaring the dependency to the internal lib should be enough to inherit its dependency to `text`. Why do we need to declare this dependency for the executable once more ?
