### ISSUE TITLE
Allow the usage of other-modules top-level

### ISSUE THREAD

**Issue by sol** [sol/hpack#402]
This will allow to e.g. disable `Path_` for a whole package:

```yaml
when:
- condition: false
  other-modules: Paths_foo

library: {}
```
