### ISSUE TITLE
Exclude modules from executable

### ISSUE THREAD

**Issue by andreasabel** [sol/hpack#421]
I tried to apply recipe #409 to `executables` but it does not seem to work.

This is the respective section of my `package.yaml` (it does not have a `library` section):
```
executables:
  LR:
    main: LR.hs
    # Exclude some files according to recipe https://github.com/sol/hpack/issues/409
    when:
      condition: false
      other-modules:
        BugLRec
        CYK
        LBNF.ErrM
        LBNF.Skel
        LBNF.Test
```

The generated `.cabal` file still contains all these modules:
```
executable LR
  main-is: LR.hs
  other-modules:
      BugLRec
      CFG
      CharacterTokenGrammar
      CYK
      DebugPrint
      LBNF.Abs
      LBNF.ErrM
      LBNF.Lex
      LBNF.Par
      LBNF.Print
      LBNF.Skel
      LBNF.Test
      ParseTable
      ParseTable.Pretty
      Saturation
      SetMaybe
      Util
      Paths_LR_demo
```

`hpack` seems to ignore `other-modules` in the `when` section altogether.

**Comment by sol** [comment]
@andreasabel it took me a while to see what's going on here.  The issue is that in your example `other-modules` is a YAML string, not a list.  If you change it to a list it should work:
```yaml
executables:
  LR:
    main: LR.hs
    # Exclude some files according to recipe https://github.com/sol/hpack/issues/409
    when:
      condition: false
      other-modules:
        - BugLRec
        - CYK
        - LBNF.ErrM
        - LBNF.Skel
        - LBNF.Test
```

In places where a list of strings is expected, Hpack treats a string literal as a singleton list.  It's convenient, but this issue demonstrates how this can be problematic. If would always require lists, your example would result in a parse error, which would be preferable in this case.

I'm not yet sure if, and if yes what we want to do about it.  Input certainly welcome!
