### ISSUE TITLE
Please accept "20150829" as a valid version number

### ISSUE THREAD

**Issue by peti** [sol/hpack#44]
Currently, hpack complains:

> package.yaml: when expecting a String, encountered Number instead

**Comment by sol** [comment]
@peti `hpack` treats versions as strings.  YAML requires string literals that start with a number to be quoted.  So I think this already works by quoting the version, e.g.:

```yaml
# package.yaml

name: foo
version: "20150829"
...
```

Have you tried this?
