### ISSUE TITLE
hackage insists on "autogen-modules" and "other-modules"

### ISSUE THREAD

**Issue by andrewufrank** [sol/hpack#442]
I want to upload a package where I use hpack to produce the cabal file. Initially I received an error from hackage indicating that autogen-modules must be also listed under other-modules. 

To get the package accepted I had to include in the `package.yaml`
````
library:
  source-dirs: 
    - .
  verbatim:
    autogen-modules:
        Paths_uniform_algebras
````
to achieve in the cabal file:
 ```
 autogen-modules: Paths_uniform_algebras
  other-modules:
      Paths_uniform_algebras
```
which satisfies hackage. It would be great if hpack would produce this automatically.
