### ISSUE TITLE
Allow duplicate fields

### ISSUE THREAD

**Issue by MrQubo** [sol/hpack#572]
Cabal supports duplicate fields in stanzas, hpack should as well.

**Comment by MrQubo** [comment]
The main problem to overcome is that YAML explicitly disallows duplicate fields. I can see two solutions.

1. Stop using YAML and use YAML-like but with duplicate fields allowed. This can be implemented without writing own parser by using libyaml package.
2. Use some valid YAML syntax for this feature, e.g.
   ```yaml
   executables:
     example:
       - main: Main.hs
       - source-dirs: src
       - ghc-options: -O2
       - ghc-options: -Wall
   ```
   or something like this:
   ```yaml
   executables:
     example:
       main: Main.hs
       source-dirs: src
       extend:
       - ghc-options: -O2
       - ghc-options: -Wall
   ```

The second solution feels a bit hacky, and I think the first one is better.

**Comment by MrQubo** [comment]
My use case is that with YAML's anchors is not possible to merge lists (e.g. ghc-options). With duplicate fields I could do:
```yaml
executables:
  example:
    main: Main.hs
    source-dirs: src
    ghc-options: *ghc-options-opt
    ghc-options: *ghc-options-warn
```

There are other solutions to my particular problem, but in my opinion, hpack should stick to be close to cabal whenever possible, as this results in less confusion for haskell developers.
