### ISSUE TITLE
When applicable, use `elif` in Cabal files

### ISSUE THREAD

**Issue by mpilgrem** [sol/hpack#604]
`elif` was introduced in `cabal-version: 2.2`. For example:

~~~yaml
when:
- condition: os(windows)
  then:
    source-dirs: windows
  else:
    when:
    - condition: "os(darwin) || os(linux)"
      then:
        source-dirs: unix-like
      else:
        source-dirs: unsupported-os
~~~

becomes:

~~~cabal
if os(windows)
  hs-source-dirs:
      windows
elif os(darwin) || os(linux)
  hs-source-dirs:
      unix-like
else
  hs-source-dirs:
      unsupported-os
~~~

I have a pull request that implements this.

**Comment by sol** [comment]
@mpilgrem this is a purely cosmetic change, right?  Or does this enable any new use cases?

**Comment by mpilgrem** [comment]
@sol, this does, de facto, only affect the readability of Cabal files. However, I think that is not unimportant: an important purpose of Cabal files is to be read by people and not all Hpack users include `package.yaml` in published packages.

I did not track down much history to the introduction of `elif`:
* in a [discussion](https://github.com/haskell/cabal/issues/3526) on multiway flags (that went nowhere), somebody observed "We should really add some `elif` sugar to Cabal 2.0 IMO to avoid those staircase if/else we currently have to endure..."; and
* `elif` was added a year later (https://github.com/haskell/cabal/pull/4750)

**Comment by mpilgrem** [comment]
(A related but distinct question is: could the Hpack format itself avoid a 'staircase'? Maybe something like:

~~~yaml
case:
- condition: os(windows)
  source-dirs: windows
- condition: os(darwin)
  source-dirs: macos
- condition: os(linux)
  source-dirs: linux
- condition: "os(freebsd) || os(openbsd) || os(netbsd)"
  source-dirs: bsd
- otherwise: # Must be last item in list
    source-dirs: unsupported-os
~~~
)

**Comment by sol** [comment]
Maybe even

```yaml
when:
  os(windows):
    source-dirs: windows
  os(darwin):
    source-dirs: macos
  os(linux):
    source-dirs: linux
  os(freebsd) || os(openbsd) || os(netbsd):
    source-dirs: bsd
  otherwise:
    source-dirs: unsupported-os
```

Just floating around ideas.
