### ISSUE TITLE
Optionally allow else branch for conditionals

### ISSUE THREAD

**Issue by sol** [sol/hpack#82]
I'm tempted to implement else-branches to conditional, e.g. accept something like the following, in addition to the current syntax:

```yaml
when:
  - condition: os(windows)
    then:
      dependencies: Win32
    else:
      dependencies: unix
```
